import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { WhiteboardProvider } from './context/WhiteboardContext'
import { EditingProvider } from './context/EditingContext'
import { DarkModeProvider } from './context/DarkModeContext'
import { AuthProvider } from './components/auth/AuthProvider'
import { ConditionalLayout } from './components/ConditionalLayout'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <DarkModeProvider>
            <EditingProvider>
              <WhiteboardProvider>
                <ConditionalLayout>{children}</ConditionalLayout>
              </WhiteboardProvider>
            </EditingProvider>
          </DarkModeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
