import type { Metadata } from 'next'
import { Inter, Noto_Serif } from 'next/font/google'
import './globals.css'
import Navigation from './components/Navigation'
import { WhiteboardProvider } from './context/WhiteboardContext'
import { EditingProvider } from './context/EditingContext'
import { DarkModeProvider } from './context/DarkModeContext'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${notoSerif.variable} antialiased`}
      >
        <DarkModeProvider>
          <EditingProvider>
            <WhiteboardProvider>
              <div className="relative flex">
                <Navigation />

                <main className="flex-1 ml-24 p-6">{children}</main>
              </div>
            </WhiteboardProvider>
          </EditingProvider>
        </DarkModeProvider>
      </body>
    </html>
  )
}
