import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navigation from './components/Navigation'
import { WhiteboardProvider } from './context/WhiteboardContext'
import { EditingProvider } from './context/EditingContext'
import { DarkModeProvider } from './context/DarkModeContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          <EditingProvider>
            <WhiteboardProvider>
              <div className="relative flex">
                <Navigation />

                <main className="flex-1 ml-24 p-6">{children}</main>
              </div>
            </WhiteboardProvider>
          </EditingProvider>
        </DarkModeProvider>
      </body>
    </html>
  )
}
